version: "3.9"
services:
  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector-dev
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
